<?php

namespace app\api\controller;

use Firebase\JWT\JWT;
use Firebase\JWT\Key;

class Base extends Cross
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        //鉴权
        //获取Token，判断Token
        $header = request()->header();
        if(!isset($header['token']) || empty($header['token'])){
           return error('token不存在',1);
        }
        $jwt = new JWT();
        $key = new Key('api123456','HS256');
        $info = $jwt::decode($header['token'], $key);
        $this->aid = $info->aid;
    }
}
