<?php

namespace app\api\controller;

use Firebase\JWT\JWT;
use Firebase\JWT\Key;
use think\facade\Env;

class Base extends Cross
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        //鉴权
        //获取Token，判断Token
        $header = request()->header();
        if(!isset($header['token']) || empty($header['token'])){
           return error('请求错误',1);
        }

        $jwt = new JWT();
        $info = $jwt::decode($header['token'], new Key(Env::get('token_key'),'HS256'));
        $this->aid = $info->aid;
        $adminInfo = db('admin')->where('id', $this->aid)->find();
        if($adminInfo['status']==0){
            return json(['code'=>250,'msg'=>'请先登录']);
        }

    }
}
