<?php

namespace app\api\controller;

use think\Controller;
use think\Request;

class Cross extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Headers: Origin, X-Requested-with, Content-Type,token, Accept, x-access-sign,x-access-time');
        header('Access-Control-Allow-Methods: GET,POST,PUT,OPTION,DELETE');
        if(request()->isOptions()){
            exit;
        }
    }
}
